# Generated by Django 5.0.6 on 2024-07-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
