# Generated by Django 5.0.6 on 2024-07-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_last_notification_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
